name: Datree
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Datree Policy Check
        uses: datreeio/action-datree@v1.0.0
        with:
          path: '*.yaml'
          cliArguments: '--only-k8s-files'